# Your specific SonarCloud project details
sonar.projectKey=amanv-ai_Repo1
sonar.organization=amanv-ai

# This tells SonarCloud it is cloud-based
sonar.host.url=https://sonarcloud.io

# Point Sonar to your notebooks folder only
sonar.sources=notebooks
